name: dentalcare
description: "Studentry - منصة الطلاب"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  flutter_bloc: ^9.1.1

  # Routing
  go_router: ^17.3.0

  # REST API
  http: ^1.5.0

  # Local Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^10.3.1
  path_provider: ^2.1.5
  path: ^1.9.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

  # Images
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  file_picker: ^12.0.0-beta.5

  # Effects & Widgets
  shimmer: ^3.0.0
  smooth_page_indicator: ^2.0.1
  fl_chart: ^1.2.0
  table_calendar: ^3.1.1
  lottie: ^3.1.2
  animate_do: ^5.1.0
  flutter_animate: ^4.5.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.4.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  mailer: ^6.1.0

  # Notifications
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.2
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.0

  # Security & Permissions
  local_auth: ^3.0.1
  permission_handler: ^12.0.3
  pdf: ^3.12.0
  printing: ^5.14.3
  syncfusion_flutter_xlsio: ^33.2.13
  share_plus: ^13.3.0
  url_launcher: ^6.3.2
  syncfusion_flutter_pdf: ^33.2.13
  google_mlkit_text_recognition: ^0.14.0
  sqflite: ^2.4.3
  sqflite_sqlcipher: ^3.4.1
  encrypt: ^5.0.3
  connectivity_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.4.11
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.4
  go_router_builder: ^4.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  adaptive_icon_background: "#0A7A8E"
  adaptive_icon_foreground: "assets/image/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0A7A8E"
  image: "assets/image/logo.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/fonts/

  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
